# Generated by Django 3.1 on 2020-11-21 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('ShippingFee', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('ShippingTime', models.IntegerField(choices=[(1, '1 day'), (3, '3 days'), (5, '5 days'), (10, '10 days')], default=10)),
                ('Is_sold', models.BooleanField(default=False)),
                ('times_viewed', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Articles_bought', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Articles_posted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('name', models.CharField(max_length=70)),
                ('condition', models.CharField(choices=[('B', 'Brand New'), ('L', 'Like New'), ('V', 'Very Good'), ('G', 'Good'), ('A', 'Acceptable')], default='B', max_length=1)),
                ('pertaining_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_article', to='app.article')),
            ],
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
                ('release_year', models.DecimalField(decimal_places=0, max_digits=5)),
                ('brand', models.CharField(max_length=70)),
                ('storage_capacity', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=70)),
            ],
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
                ('release_year', models.DecimalField(decimal_places=0, max_digits=5)),
                ('publisher', models.CharField(max_length=70)),
                ('genre', models.CharField(max_length=70)),
                ('rating', models.CharField(choices=[('E', 'Everyone'), ('T', 'Teen'), ('M', 'Mature'), ('A', 'Adult')], default='E', max_length=1)),
                ('platform', models.CharField(blank=True, choices=[('PS', 'Playstation'), ('XB', 'Xbox One'), ('SW', 'Nintendo'), ('PC', 'Computer'), ('WI', 'Wii'), ('RT', 'Retro')], max_length=2)),
            ],
            bases=('app.item',),
        ),
    ]
