# Generated by Django 3.1 on 2020-11-10 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='buyer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Articles_bought', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='times_viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000000000),
        ),
        migrations.AlterField(
            model_name='item',
            name='pertaining_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_article', to='app.article'),
        ),
    ]
