# Generated by Django 3.1 on 2020-11-24 01:58

import app.models
import app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, storage=app.storage.OverwriteStorage(), upload_to=app.models.user_item_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, storage=app.storage.OverwriteStorage(), upload_to=app.models.user_profile_path),
        ),
    ]
