# Generated by Django 3.1 on 2020-11-25 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Date_Posted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
